[package]
name = "sentry-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "sentry"
path = "src/main.rs"

[dependencies]
sentry-daemon = { path = "../sentry-daemon" }
sentry-policy = { path = "../sentry-policy" }
